In [141]:
# Importing the Packages
import numpy as np

In [142]:
np.set_printoptions(suppress=  True, linewidth= 100, precision= 2)

In [143]:
# Importing the data
raw_data_np = np.genfromtxt('Loan data.csv', delimiter= ';', skip_header=True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [144]:
# Checking for Incomplete Data
np.isnan(raw_data_np).sum()

88005

In [145]:
temp_fill = np.nanmax(raw_data_np) + 1
temp_mean = np.nanmean(raw_data_np, axis= 0)

C:\Users\mk744\AppData\Local\Temp\ipykernel_21556\3463555020.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_np, axis= 0)


In [146]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [147]:
temp_stats = np.array([np.nanmin(raw_data_np, axis= 0),
                       temp_mean, 
                       np.nanmax(raw_data_np, axis= 0)])

C:\Users\mk744\AppData\Local\Temp\ipykernel_21556\3687959860.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data_np, axis= 0),
C:\Users\mk744\AppData\Local\Temp\ipykernel_21556\3687959860.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis= 0)])


In [148]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [149]:
# Splitting the string data and numeric data seperately
# Splitting the Columns
# use squeeze method to display the data in 1 - D
columns_strings = np.argwhere(np.isnan(temp_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [150]:
columns_numerics = np.argwhere(np.isnan(temp_mean)==False).squeeze()
columns_numerics

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [151]:
# Re-importing the Dataset
# Importing the data
Loan_data_strings = np.genfromtxt('Loan data.csv',
                            delimiter= ';',
                            skip_header= 1, 
                            autostrip=True,
                            usecols= columns_strings,
                            dtype= np.str_)
Loan_data_strings


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [152]:
Loan_data_numeric = np.genfromtxt('Loan data.csv',
                            delimiter= ';',
                            skip_header= 1, 
                            autostrip=True,
                            usecols= columns_numerics,
                            filling_values=temp_fill)
Loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [153]:
# The Names of the Colums
header_full = np.genfromtxt('Loan data.csv',
                            delimiter= ';',
                            skip_footer= raw_data_np.shape[0], 
                            autostrip=True,
                            dtype= np.str_)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [154]:
header_strings, header_numeric = header_full[columns_strings],header_full[columns_numerics]

In [155]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [156]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [157]:
# Creating Checkpoint (to save data)
def checkpoint(file_name, checkpoint_header, checkpoint_data):
     np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
     checkpoint_variable = np.load(file_name + ".npz")
     return(checkpoint_variable)

In [158]:
checkpoint_test = checkpoint("checkpoint-test",
                             header_strings, Loan_data_strings)

In [159]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [160]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [161]:
np.array_equal(checkpoint_test['data'], Loan_data_strings)

True

In [162]:
# Manipulating String Columns
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [163]:
header_strings[0] = "issue_date"

In [164]:
Loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [165]:
# Print issue Date data
np.unique(Loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [166]:
Loan_data_strings[:,0] = np.chararray.strip(Loan_data_strings[:,0], "-15")

In [167]:
np.unique(Loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [168]:
months = np.array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'])

In [169]:
for i in range(13):
     Loan_data_strings[:,0] = np.where(Loan_data_strings[:,0]==months[i],
                                       i, Loan_data_strings[:,0])

In [170]:
np.unique(Loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [171]:
# Loan Status
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [172]:
np.unique(Loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [173]:
np.unique(Loan_data_strings[:,1]).size

9

In [174]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)' ])

In [175]:
Loan_data_strings[:,1] = np.where(np.isin(Loan_data_strings[:,1], status_bad), 0,1)

In [176]:
np.unique(Loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [177]:
#Terms 
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [178]:
np.unique(Loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [179]:
np.unique(Loan_data_strings[:,2]).size

3

In [180]:
Loan_data_strings[:,2] = np.chararray.strip(Loan_data_strings[:,2], "months")
Loan_data_strings[:,2]

array(['36 ', '36 ', '36 ', ..., '36 ', '36 ', '36 '], dtype='<U69')

In [181]:
header_strings[2] = "term_months"

In [182]:
Loan_data_strings[:,2] = np.where(Loan_data_strings[:,2]=='',
                                  '60',
                                  Loan_data_strings[:,2])
Loan_data_strings[:,2]

array(['36 ', '36 ', '36 ', ..., '36 ', '36 ', '36 '], dtype='<U69')

In [183]:
np.unique(Loan_data_strings[:,2])

array(['36 ', '60', '60 '], dtype='<U69')

In [184]:
# Grade and Subgrade
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [185]:
np.unique(Loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [186]:
np.unique(Loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [187]:
# Filling Sub Grade
for i in np.unique(Loan_data_strings[:,3])[1:]:
     Loan_data_strings[:,4] = np.where((Loan_data_strings[:,4]=='') & (Loan_data_strings[:,3]==i),
                   i + '5',
                   Loan_data_strings[:,4])

In [188]:
np.unique(Loan_data_strings[:,4], return_counts= True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [189]:
Loan_data_strings[:,4] = np.where(Loan_data_strings[:,4]=='',
                    'H1',
                   Loan_data_strings[:,4])

In [190]:
np.unique(Loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [191]:
# Removing Grade
Loan_data_strings = np.delete(Loan_data_strings, 3, axis= 1)

In [192]:
Loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [193]:
header_strings = np.delete(header_strings, 3)

In [194]:
header_strings[3]

'sub_grade'

In [195]:
# Converting Sub Grade
np.unique(Loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [196]:
keys = list(np.unique(Loan_data_strings[:,3]))
values = list(range(1, np.unique(Loan_data_strings[:,3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, values))

In [197]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [198]:
for i in np.unique(Loan_data_strings[:,3]):
     Loan_data_strings[:,3] = np.where(Loan_data_strings[:,3]==i,
                                       dict_sub_grade[i],
                                       Loan_data_strings[:,3])

In [199]:
np.unique(Loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [200]:
# Verification Status
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [201]:
np.unique(Loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [202]:
Loan_data_strings[:,4] = np.where((Loan_data_strings[:,4]=='') | (Loan_data_strings[:,4]=='Not Verified'), 0, 1)

In [203]:
np.unique(Loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

In [204]:
# URL
Loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [205]:
np.chararray.strip(Loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [206]:
Loan_data_strings[:,5]=np.chararray.strip(Loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [207]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [208]:
Loan_data_numeric[:,0].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [209]:
Loan_data_strings[:,5].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [210]:
np.array_equal(Loan_data_numeric[:,0].astype(dtype=np.int32), Loan_data_strings[:,5].astype(dtype=np.int32))

True

In [211]:
Loan_data_strings = np.delete(Loan_data_strings, 5, axis=1)
header_strings = np.delete(header_strings, 5)

In [212]:
Loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [213]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [214]:
Loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [215]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [216]:
# State Address
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [217]:
header_strings[5] = "state_address"

In [218]:
states_name, states_count=np.unique(Loan_data_strings[:,5], return_counts=True)
states_count_sorted = np.argsort(-states_count)
states_name[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [219]:
Loan_data_strings[:,5] = np.where(Loan_data_strings[:,5]== '',
                                  0,
                                  Loan_data_strings[:,5])

In [220]:
states_west = np.array(['WA','OR','CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK'])
states_south = np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC'])
states_midwest = np.array(['ND', 'SD','NE', 'KS', 'MN', 'IA','MO', 'WI', 'IL','IN','MI','OH'])
states_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI'])

In [221]:
Loan_data_strings[:, 5] = np.where(np.isin(Loan_data_strings[:,5], states_west), 1, Loan_data_strings[:,5])
Loan_data_strings[:, 5] = np.where(np.isin(Loan_data_strings[:,5], states_south), 2, Loan_data_strings[:,5])
Loan_data_strings[:, 5] = np.where(np.isin(Loan_data_strings[:,5], states_midwest), 3, Loan_data_strings[:,5])
Loan_data_strings[:, 5] = np.where(np.isin(Loan_data_strings[:,5], states_east), 4, Loan_data_strings[:,5])

In [222]:
np.unique(Loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [223]:
# Converting to Numbers
Loan_data_strings

array([['9', '1', '36 ', '13', '1', '1'],
       ['0', '1', '36 ', '5', '1', '4'],
       ['12', '1', '36 ', '10', '1', '4'],
       ...,
       ['7', '1', '36 ', '5', '1', '1'],
       ['1', '1', '36 ', '17', '1', '3'],
       ['3', '1', '36 ', '4', '0', '3']], dtype='<U69')

In [224]:
Loan_data_strings = Loan_data_strings.astype(np.int32)

In [225]:
Loan_data_strings

array([[ 9,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [12,  1, 36, 10,  1,  4],
       ...,
       [ 7,  1, 36,  5,  1,  1],
       [ 1,  1, 36, 17,  1,  3],
       [ 3,  1, 36,  4,  0,  3]])

In [226]:
# checkpoint 1: String
checkpoint_strings = checkpoint('Checkpoint-String', header_strings, Loan_data_strings)

In [227]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [228]:
checkpoint_strings['data']

array([[ 9,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [12,  1, 36, 10,  1,  4],
       ...,
       [ 7,  1, 36,  5,  1,  1],
       [ 1,  1, 36, 17,  1,  3],
       [ 3,  1, 36,  4,  0,  3]])

In [229]:
np.array_equal(checkpoint_strings['data'], Loan_data_strings)

True

In [230]:
# Manipulating Numeric Columns
Loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [231]:
np.isnan(Loan_data_numeric).sum()

0

In [232]:
# Substitute 'Filler' value
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [233]:
# ID
temp_fill

68616520.0

In [234]:
np.isin(Loan_data_numeric[:,0], temp_fill)

array([False, False, False, ..., False, False, False])

In [235]:
np.isin(Loan_data_numeric[:,0], temp_fill).sum()

0

In [236]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [237]:
# Temporary Stats
temp_stats[:,columns_numerics]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [238]:
# Funded amount
Loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [239]:
Loan_data_numeric[:,2] = np.where(Loan_data_numeric[:,2]==temp_fill,
                                  temp_stats[0,columns_numerics[2]],
                                  Loan_data_numeric[:,2])
Loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [240]:
temp_stats[0,columns_numerics[3]]

6.0

In [241]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [242]:
for i in[1,3,4,5]:
     Loan_data_numeric[:,i] = np.where(Loan_data_numeric[:,i]==temp_fill,
                                       temp_stats[2, columns_numerics[i]],
                                       Loan_data_numeric[:,i])

In [243]:
Loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [245]:
# Currency Change
# The Exchange Rate
EUR_USD = np.genfromtxt('EUR.csv', delimiter=',',autostrip = True, skip_header=1, usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [246]:
Loan_data_strings[:,0]

array([ 9,  0, 12, ...,  7,  1,  3])

In [247]:
exchange_rate = Loan_data_strings[:,0]
for i in range(1,13):
     exchange_rate = np.where(exchange_rate == i,
                              EUR_USD[i-1],
                              exchange_rate)
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)
exchange_rate

array([1.13, 1.11, 1.09, ..., 1.09, 1.13, 1.08])

In [248]:
exchange_rate.shape

(10000,)

In [249]:
Loan_data_numeric.shape

(10000, 6)

In [250]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [253]:
Loan_data_numeric = np.hstack((Loan_data_numeric, exchange_rate))

In [254]:
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [255]:
# From USD to EUR
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [256]:
columns_dollar = np.array([1,2,4,5])

In [257]:
Loan_data_numeric[:,6]

array([1.13, 1.11, 1.09, ..., 1.09, 1.13, 1.08])

In [258]:
for i in columns_dollar:
     Loan_data_numeric=np.hstack((Loan_data_numeric, np.reshape(Loan_data_numeric[:,i]/Loan_data_numeric[:,6], (10000, 1))))

In [259]:
Loan_data_numeric.shape

(10000, 11)

In [260]:
Loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31094.7 ,     1052.65,     8398.2 ],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13718.7 ,      452.59,     1801.57],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     9141.4 ,     1255.09,     1997.98],
       [46154151.  ,    35000.  ,    10000.  , ...,     8859.  ,      313.87,     2834.35],
       [66055249.  ,    10000.  ,    10000.  , ...,     9233.4 ,      286.21,      278.76]])

In [261]:
# Expanding the header
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])

In [262]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [264]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [265]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [266]:
# Expanding the header
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])

In [267]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [270]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [271]:
header_numeric[columns_index_order]

array(['id', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt', 'funded_amnt_EUR', 'int_rate',
       'installment', 'installment_EUR', 'total_pymnt', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [272]:
Loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31094.7 ,     1052.65,     8398.2 ],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13718.7 ,      452.59,     1801.57],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     9141.4 ,     1255.09,     1997.98],
       [46154151.  ,    35000.  ,    10000.  , ...,     8859.  ,      313.87,     2834.35],
       [66055249.  ,    10000.  ,    10000.  , ...,     9233.4 ,      286.21,      278.76]])

In [273]:
Loan_data_numeric = Loan_data_numeric[:,columns_index_order]

In [274]:
# Interest Rate
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [275]:
Loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [276]:
Loan_data_numeric[:,5] = Loan_data_numeric[:,5]/100

In [277]:
Loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

In [278]:
checkpoint_numeric = checkpoint('Checkpoint-Numeric', header_numeric, Loan_data_numeric)

In [279]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
        'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31094.7 , ...,     9452.96,     8398.2 ,        1.13],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13718.7 , ...,     1969.83,     1801.57,        1.09],
        ...,
        [50415990.  ,    10000.  ,     9141.4 , ...,     2185.64,     1997.98,        1.09],
        [46154151.  ,    35000.  ,    31006.5 , ...,     3199.4 ,     2834.35,        1.13],
        [66055249.  ,    10000.  ,     9233.4 , ...,      301.9 ,      278.76,        1.08]]))

In [280]:
# Creating the "Complete" Dataset
checkpoint_strings['data'].shape

(10000, 6)

In [281]:
checkpoint_numeric['data'].shape

(10000, 11)

In [282]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data'])) 

In [283]:
np.isnan(loan_data).sum()

0

In [285]:
header_full=np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

In [286]:
# Sorting the New Dataset
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [287]:
loan_data

array([[  373332.  ,     9950.  ,     9401.85, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    11338.92, ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8997.4 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5170.7 , ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3693.36, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19944.14, ...,        3.  ,        0.  ,        2.  ]])

In [288]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [290]:
# Storing the New Dataset
loan_data = np.vstack((header_full, loan_data))

In [291]:
np.savetxt("loan-data-preprocessed.csv",
           loan_data,
           fmt = "%s",
           delimiter= ',')

: 